#!/bin/bash

# Colors

RED='\e[31m'
GREEN='\e[92m'
MAGENTA='\e[95m'
NC='\e[0m'
WHITE='\e[97m'


# Check for log directory and create it if it doesn't already exist.

logDir=$HOME/logs/ping

if 
	[ -d "$logDir" ]; then
	echo "Found the logs! Feels like Minecraft." > /dev/null
else
	mkdir -P $logDir
	echo "Log directory created at $logDir."
fi

# Cleanup function that will output the statistics of the ping command.

cleanup () {
        sleep 1
        echo
        grep -A 3 "ping" $logDir/$outputFile
}


# Capture file name and check for duplicates before reading address and pinging host.

ip=$1
count=""

echo -e $MAGENTA
echo "Enter a name for the generated log file:"
read fileName

outputFile=$(date +%Y-%m-%d_%H:%M_)$fileName.txt
dupeCheck=$logDir/$outputFile

if 
	[ -f "$dupeCheck" ]; then
	((count++))
	outputFile=$(date +%Y-%m-%d_%H:%M_)$fileName$count.txt
fi

echo -e $WHITE
echo "File to be generated: $logDir/$outputFile"
echo


# Ping address and write all lines to file, then read file back to user line-by-line.

ping -O $ip | while read -r line; do

        if [[ $line =~ PING ]] ; then
                echo -e $WHITE------------------------------------------------------------------------
                echo $line
                echo -e $NC------------------------------------------------------------------------
        elif [[ $line =~ ttl ]] ; then
                echo -e $GREEN$line
        elif [[ $line =~ ping ]] || [[ $line =~ rtt ]] || [[ $line =~ packet ]] ; then
                echo -e $WHITE$line
        else
                echo -e $RED$line

        fi >> $logDir/$outputFile

        tail -1 $logDir/$outputFile

        trap cleanup SIGINT
done
